### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by joemphilips** [campfire-inc/OKIMOCHI#1]
## Dev

- [x] 全額引き出そうとすると(おそらく手数料の問題で)引き出せなくなる問題の修正
- [ ] 「ありがとう」などの言葉に反応してtipする機能(pay by gratitude) ... 実装し直し
- [x] ポンチ絵作成
- [x] bitcoindの `walletnotify` 機能で、confirmation時にwebhookを送る
- [x] registerしていない相手にも支払えるようにする。
- [x] register時にimportaddressしていたのをやめる
- [x] ~~自前のmongodbの代わりに[bitcore](https://bitcore.io/guides/wallet-service/) のwallet機能を使う~~ bitcoreは保守されていないので却下
- [ ] `tip` 時のデフォルト支払い量を100円にする
- [x] 支払い時のメッセージ(や、deposit、register)を同じチャンネルではなくダイレクトメッセージで送る。
- [ ] `withdraw` を叩いた時にpendingBalanceを自動で表示
- [ ] `withdraw` でAllを指定できるようにする
- [ ] 複数回ボタンを押された時に、最初の一回だけでなく全てに反応するようにする。
- [ ] messageをstarした際にも支払う
- [ ] 管理者が承認した場合のみトランザクションを発行するモードの追加
- [x] withdraw時のconversationを `convo.repeat()` を使用したより直感的なものに変更する。
- [x] `balance` をなくし、 `ranking` にする。
 * depositと受け取ったお気持ちの量の２つを出す。
 * plotlyを使う
- [x] deposit 時にユーザー情報をDB側に登録
- [x] dbのハンドラをbotkitの `controller.storage` 機能からnative mongo driverに変更する。(あまりに低機能すぎてアップデート時の実装が汚いため) -> 結局 `mongoose` にした
- [x] `bitcoin-core`の`RpcError`をcatchできないバグの修正 ... (bitcoreへの移行を検討する)
- [x] pay intentionally
- [ ].LNでの送金に対応
- [ ] テストの実装
- [x] get payment address ... どのアドレスが使用済みかも含む
- [x] depositランキングの表示
- [x] deposit時にQR codeを表示
- [x] pay by gratitudeの場合とpay intentionally(tip) の場合での関数の共通化
- [x] OKIMOCHIランキングの表示
- [x] ランキング中のユーザー名をhuman readableにする
- [ ] slashコマンドの挙動確認
- [ ] `/payvote_who` でボタンを押した相手にokimochiを遅れる機能の追加
- [ ] `/payvote_howmuch` でいくら送るべきか投票で決める機能の追加
- [x] `winston` logger の追加
- [ ] litecoin,monacoinへの対応
- [ ] baramaki機能の追加
- [x] 日本語化への対応
- [ ] 円での表示
- [ ] `rate` をもっと頑張る

## Ops

- [x] テスト自動化
- [x] ECSでの実行
- [x] デプロイ自動化
- [ ] circleciでのキャッシュの使用
- [x] `docker build` 時の時間短縮のため、データベースディレクトリを`okimochi`自体のビルドコンテキストから外す
- [x] linksが有効に機能しないので、（[公式でdeprecatedらしい](http://docs.docker.jp/compose/networking.html)）カスタムのネットワークにする (ECSではlinkが有効なのでそちらを使用する。)
- [x] deploy時のスラックへの通知
- [x] localとecsでの環境の切り替え
- [x] ecs上のコンテナのログを改善
- [ ] debugログなども全てロガーで出力する
- [ ] winstonのnamespaceを洗練されたものにする

## セキュリティ

- [x] IPアドレスでのアクセス制限
- [ ] `-rpcusername`, `-rpcpassword` の代わりにcookieベースの認証へ移行
- [x] (その後)メインネットへの移行

**Comment by joemphilips** [comment]
#22 に以降
