### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by joemphilips** [campfire-inc/OKIMOCHI#22]
* [ ] trigger payment automatically when someone show gratitude to someone else.
* [ ] set default `tip` amount.
* [ ] add tests.
* [ ] show pending Balance when `withdraw`
* [ ] withdraw all balance by default.
* [ ] implement configure option to send actual TX only when the administrator has approved.
* [ ] add simple poll method for deciding how much to pay and who to pay by slash command.
* [ ] enable to use litecoin.
* [ ] elaborate `rate` command.
* [ ] stop using plotly.
* [ ]  use cache for CI.
* [ ] use cookie based authentication instead of custom username and password
